### ISSUE TITLE
WindowResizer: Visual glitches when going into full-screen mode

### ISSUE THREAD

**Issue by SunSerega** [SokuDev/SokuMods#16]
This was asked many times in Touhou 12.3 Hisoutensoku discord server, but I wanted to make the issue, so it's more trackable and not forgotten about.

When I go to full-screen mode with WindowResizer enabled:
![image](https://user-images.githubusercontent.com/27270190/114204203-983dda80-9961-11eb-978d-0778a207c5fe.png)
Red shown corners of the usable screen - it ends up being less than standard 640x480.
Green shows that the outer strip contains a piece of the button selecting cogwheel, left from when the game was windowed.

**Comment by delthas** [comment]
Yup, it's already fixed but we haven't released a new version with the bugfix yet.
